// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RPImobiliaria.Data;

#nullable disable

namespace RPImobiliaria.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803190140_InicialParaSQLite")]
    partial class InicialParaSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RPImobiliaria.Models.Caracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GrupoCaracteristicaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GrupoCaracteristicaId");

                    b.ToTable("CaracteristicasCatalogo");
                });

            modelBuilder.Entity("RPImobiliaria.Models.CategoriaImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CategoriasImovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.CertificadoEnergetico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CertificadosEnergeticos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoFotoPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telemovel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Concelho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DistritoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Concelhos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Consultor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoFotoPerfil")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTypeFoto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LicencaAMI")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telemovel")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Consultores");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Distrito", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Distritos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.DocumentoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoFicheiro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeFicheiro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("Documentos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.EstadoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EstadosImovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.FichaCliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotasRequisitos")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OrcamentoMaximo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PerfilArrendatario")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerfilComprador")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerfilInvestidor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PerfilVendedor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PreenchidoPeloCliente")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TipologiasProcuradas")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UltimaAtualizacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("ZonasPreferencia")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.ToTable("FichasClientes");
                });

            modelBuilder.Entity("RPImobiliaria.Models.FotoImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ordem")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ImovelId");

                    b.ToTable("Fotos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Freguesia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConcelhoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ConcelhoId");

                    b.ToTable("Freguesias");
                });

            modelBuilder.Entity("RPImobiliaria.Models.GrupoCaracteristica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("GruposCaracteristicas");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Imovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnoConstrucao")
                        .HasColumnType("INTEGER");

                    b.Property<double>("AreaBruta")
                        .HasColumnType("REAL");

                    b.Property<double>("AreaUtil")
                        .HasColumnType("REAL");

                    b.Property<int>("CasasBanho")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriaImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CertificadoEnergeticoId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConsultorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("Estacionamento")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EstadoImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FreguesiaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MoradaExata")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumeroContrato")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroFrentes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObservacoesInternas")
                        .HasColumnType("TEXT");

                    b.Property<int>("Piso")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quartos")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Referencia")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StatusImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TipoNegocioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ValorComissao")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Zona")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaImovelId");

                    b.HasIndex("CertificadoEnergeticoId");

                    b.HasIndex("ConsultorId");

                    b.HasIndex("EstadoImovelId");

                    b.HasIndex("FreguesiaId");

                    b.HasIndex("StatusImovelId");

                    b.HasIndex("TipoNegocioId");

                    b.ToTable("Imoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelCaracteristica", b =>
                {
                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaracteristicaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImovelId", "CaracteristicaId");

                    b.HasIndex("CaracteristicaId");

                    b.ToTable("ImoveisCaracteristicas");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelFavorito", b =>
                {
                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAdicionado")
                        .HasColumnType("TEXT");

                    b.HasKey("ImovelId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ImoveisFavoritos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelProprietario", b =>
                {
                    b.Property<int>("ImovelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImovelId", "ClienteId");

                    b.HasIndex("ClienteId");

                    b.ToTable("ImoveisProprietarios");
                });

            modelBuilder.Entity("RPImobiliaria.Models.StatusImovel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StatusImoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.TipoNegocio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TiposNegocio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RPImobiliaria.Models.Caracteristica", b =>
                {
                    b.HasOne("RPImobiliaria.Models.GrupoCaracteristica", "GrupoCaracteristica")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("GrupoCaracteristicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GrupoCaracteristica");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Concelho", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Distrito", "Distrito")
                        .WithMany("Concelhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("RPImobiliaria.Models.DocumentoImovel", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Imovel", "Imovel")
                        .WithMany("Documentos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.FichaCliente", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Cliente", "Cliente")
                        .WithOne("Ficha")
                        .HasForeignKey("RPImobiliaria.Models.FichaCliente", "ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("RPImobiliaria.Models.FotoImovel", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Imovel", "Imovel")
                        .WithMany("Fotos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Freguesia", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Concelho", "Concelho")
                        .WithMany("Freguesias")
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Concelho");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Imovel", b =>
                {
                    b.HasOne("RPImobiliaria.Models.CategoriaImovel", "CategoriaImovel")
                        .WithMany("Imoveis")
                        .HasForeignKey("CategoriaImovelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RPImobiliaria.Models.CertificadoEnergetico", "CertificadoEnergetico")
                        .WithMany("Imoveis")
                        .HasForeignKey("CertificadoEnergeticoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RPImobiliaria.Models.Consultor", "Consultor")
                        .WithMany("ImoveisAngariados")
                        .HasForeignKey("ConsultorId");

                    b.HasOne("RPImobiliaria.Models.EstadoImovel", "EstadoImovel")
                        .WithMany("Imoveis")
                        .HasForeignKey("EstadoImovelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RPImobiliaria.Models.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RPImobiliaria.Models.StatusImovel", "StatusImovel")
                        .WithMany("Imoveis")
                        .HasForeignKey("StatusImovelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RPImobiliaria.Models.TipoNegocio", "TipoNegocio")
                        .WithMany("Imoveis")
                        .HasForeignKey("TipoNegocioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaImovel");

                    b.Navigation("CertificadoEnergetico");

                    b.Navigation("Consultor");

                    b.Navigation("EstadoImovel");

                    b.Navigation("Freguesia");

                    b.Navigation("StatusImovel");

                    b.Navigation("TipoNegocio");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelCaracteristica", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Caracteristica", "Caracteristica")
                        .WithMany("ImoveisCaracteristicas")
                        .HasForeignKey("CaracteristicaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RPImobiliaria.Models.Imovel", "Imovel")
                        .WithMany("Caracteristicas")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Caracteristica");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelFavorito", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Cliente", "Cliente")
                        .WithMany("Favoritos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPImobiliaria.Models.Imovel", "Imovel")
                        .WithMany("Favoritos")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.ImovelProprietario", b =>
                {
                    b.HasOne("RPImobiliaria.Models.Cliente", "Cliente")
                        .WithMany("ImoveisPropriedade")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RPImobiliaria.Models.Imovel", "Imovel")
                        .WithMany("Proprietarios")
                        .HasForeignKey("ImovelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Imovel");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Caracteristica", b =>
                {
                    b.Navigation("ImoveisCaracteristicas");
                });

            modelBuilder.Entity("RPImobiliaria.Models.CategoriaImovel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.CertificadoEnergetico", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Cliente", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Ficha");

                    b.Navigation("ImoveisPropriedade");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Concelho", b =>
                {
                    b.Navigation("Freguesias");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Consultor", b =>
                {
                    b.Navigation("ImoveisAngariados");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Distrito", b =>
                {
                    b.Navigation("Concelhos");
                });

            modelBuilder.Entity("RPImobiliaria.Models.EstadoImovel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.GrupoCaracteristica", b =>
                {
                    b.Navigation("Caracteristicas");
                });

            modelBuilder.Entity("RPImobiliaria.Models.Imovel", b =>
                {
                    b.Navigation("Caracteristicas");

                    b.Navigation("Documentos");

                    b.Navigation("Favoritos");

                    b.Navigation("Fotos");

                    b.Navigation("Proprietarios");
                });

            modelBuilder.Entity("RPImobiliaria.Models.StatusImovel", b =>
                {
                    b.Navigation("Imoveis");
                });

            modelBuilder.Entity("RPImobiliaria.Models.TipoNegocio", b =>
                {
                    b.Navigation("Imoveis");
                });
#pragma warning restore 612, 618
        }
    }
}
